# Generated by Django 4.2.4 on 2024-01-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_customuser_copper_username_alter_customuser_universe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='copper_username',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Nombre de usuario en Coppermind'),
        ),
    ]
