# Generated by Django 4.2.15 on 2025-03-03 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_app', '0003_alter_customuser_copper_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Glossary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordEn', models.CharField(max_length=200, verbose_name='Palabra inglés')),
                ('wordEs', models.CharField(blank=True, max_length=200, null=True, verbose_name='Palabra español')),
                ('urlEn', models.URLField(blank=True, max_length=2000, null=True, verbose_name='Enlace Coppermind en inglés')),
                ('urlEs', models.URLField(blank=True, max_length=2000, null=True, verbose_name='Enlace Coppermind en español')),
                ('universe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='glossary_universe', to='login_app.universe', verbose_name='Universo')),
            ],
            options={
                'verbose_name': 'Glosario',
                'verbose_name_plural': 'Glosario',
            },
        ),
    ]
