services:
  postgres-db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/

    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'mentecobre'

    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 2s
      timeout: 5s
      retries: 10

  web:
    build:
      context: ../
      dockerfile: docker-files/Dockerfile
    env_file:
      - ../.env
    volumes:
      - ..:/app
    depends_on:
      postgres-db:
        condition: service_healthy

    ports:
      - "8000:8000"
volumes:
    postgres_data: